version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  spark:
    image: bitnami/spark:3
    ports:
      - "4040:4040"

  heart_rate_producer:
    build: .
    command: python producer/heart_rate_producer.py
    depends_on:
      - kafka

  body_temp_producer:
    build: .
    command: python producer/body_temperature_producer.py
    depends_on:
      - kafka

  bp_producer:
    build: .
    command: python producer/blood_pressure_producer.py
    depends_on:
      - kafka

  oxygen_producer:
    build: .
    command: python producer/peripheral_oxygen_saturation_producer.py
    depends_on:
      - kafka

  consumer:
    build: .
    command: python consumer/consumer.py
    depends_on:
      - kafka
      - spark
