services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark:
    image: bitnami/spark:latest
    ports:
      - "4040:4040"

  heart_rate_producer:
    build: .
    command: python producers/heart_rate_producer.py
    depends_on:
      - kafka

  body_temp_producer:
    build: .
    command: python producers/body_temperature_producer.py
    depends_on:
      - kafka

  bp_producer:
    build: .
    command: python producers/blood_pressure_producer.py
    depends_on:
      - kafka

  oxygen_producer:
    build: .
    command: python producers/peripheral_oxygen_saturation_producer.py
    depends_on:
      - kafka

  consumer:
    build: .
    command: python consumer/consumer.py
    depends_on:
      - kafka
      - spark
